baseurl = "http://localhost:1313/"
DefaultContentLanguage = "en"
title = "~prologic"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsStyle = "vim"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentOptions = "linenos=inline"

[Params]
  subtitle = "Problems are solved by method"
  logo = "logo.png"
  favicon = "favicon.png"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  readingTime = true
  useHLJS = true

[Author]
  name = "James Mills"
  website = "prologic.shortcircuit.net.au"
  email = "prologic@shortcircuit.net.au"
  facebook = "therealprologic"
  twitter = "therealprologic"
  googleplus = "+JamesMillsprologic"
  github = "prologic"
  linkedin = "prologic"
  stackoverflow = "users/364980/james-mills"

[[menu.main]]
  name = "Posts"
  url = ""
  weight = 1

[[menu.main]]
  name = "Projects"
  url = "page/Projects"
  weight = 2

[[menu.main]]
  name = "About"
  url = "page/about/"
  weight = 3

[[menu.main]]
  name = "Tags"
  url = "tags"
  weight = 3
